-- Placeholder initial migration
-- Please run 'npx prisma migrate dev --name init' to generate a proper initial migration
-- based on your schema.prisma file.

-- This file would normally contain:
-- CREATE TABLE "Collection" (
--     "id" TEXT NOT NULL PRIMARY KEY,
--     "name" TEXT NOT NULL,
--     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
-- );
-- CREATE TABLE "Flashcard" (
--     "id" TEXT NOT NULL PRIMARY KEY,
--     "question" TEXT NOT NULL,
--     "answer" TEXT NOT NULL,
--     "imageUrl" TEXT,
--     "collectionId" TEXT,
--     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     "updatedAt" TIMESTAMP(3) NOT NULL,
--     "timesViewed" INTEGER NOT NULL DEFAULT 0,
--     "timesCorrect" INTEGER NOT NULL DEFAULT 0,
--     CONSTRAINT "Flashcard_collectionId_fkey" FOREIGN KEY ("collectionId") REFERENCES "Collection" ("id") ON DELETE SET NULL ON UPDATE CASCADE
-- );
-- CREATE UNIQUE INDEX "Collection_name_key" ON "Collection"("name");
